@startuml
actor Player
participant "GameController" as GC
participant "PokerGame" as Game
participant "BettingUI" as UI

Player -> UI : Plasează pariu
UI -> GC : Send bet action(player, sum)
GC -> Game : Process bet(player, sum)
Game -> GC : Action response (Valid Bet/ Invalid Bet)
GC -> UI : Update UI (Bet Result)
UI -> Player : Show bet result

@enduml
