@startuml
left to right direction

actor "Jucator" as Player

rectangle "Sistem Poker Game" {
    (Autentificare)
    (Vizualizare lobby)
    (Alaturare joc)
    (Incepe joc)
    (Plaseaza pariu)
    (Vede carțile)
    (Vede rezultatul mainii)
    (Ieșire joc)
}

Player --> (Autentificare)
Player --> (Vizualizare lobby)
Player --> (Alaturare joc)
Player --> (Incepe joc)
Player --> (Plaseaza pariu)
Player --> (Vede carțile)
Player --> (Vede rezultatul mainii)
Player --> (Ieșire joc)



@enduml
