@startuml
left to right direction

actor "Player" as Player

rectangle "Poker Game System" {
    (Authentification)
    (Lobby visualisation)
    (Join game)
    (Start game)
    (Place bet)
    (See cards)
    (See hand result)
    (Exit game)
}

Player --> (Authentification)
Player --> (Lobby visualisation)
Player --> (Join game)
Player --> (Start game)
Player --> (Place bet)
Player --> (See cards)
Player --> (See hand result)
Player --> (Exit game)



@enduml
