@startuml
start

:Game initialization;

:Cards are dealt to players;

partition "Pre-Flop" {
    :Pre-Flop;
}

partition "Flop" {
    :Adding 3 cards;
    :Bets;
}

partition "Turn" {
    :4th card is added;
    :Bets;
}

partition "River" {
    :5th card is added;
    :Last bets;
}

:Showdown (the winner is determined);

:Pot is awarded to the winner;

:Verifying if there are still players with chips;
if (Players still have chips) then (Yes)
    :Begin new round;
    -> [back] start
else (No)
    :End game;
    stop
endif

@enduml
