name: Generate PlantUML Diagrams

on:
  push:
    paths:
      - 'docs/**/*.puml'
      - '.github/workflows/generate-plantuml-diagrams.yml'
  pull_request:
    paths:
      - 'docs/**/*.puml'

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download PlantUML
        run: curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2024.6/plantuml-1.2024.6.jar

      - name: Generate PNG diagrams from .puml files
        run: |
          mkdir -p docs/generated_diagrams
          find docs -name '*.puml' -exec java -jar plantuml.jar -tpng -o generated_diagrams {} \;

      - name: Commit and push generated diagrams
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/generated_diagrams/
          git commit -m "Auto-generate PlantUML diagrams [skip ci]" || echo "No changes to commit"
          git push
